tags:
  - manifests
operationId: manifests.list
parameters:
  - $ref: '../../../parameters.yaml#/warehouse_id_query_param'
  - name: ship_date_start
    in: query
    required: false
    schema:
      type: string
      format: date-time
  - name: ship_date_end
    in: query
    required: false
    schema:
      type: string
      format: date-time
  - $ref: '../../../parameters.yaml#/created_at_start_query_param'
  - $ref: '../../../parameters.yaml#/created_at_end_query_param'
  - $ref: '../../../parameters.yaml#/carrier_id_query_param'
  - $ref: '../../../parameters.yaml#/page_query_param'
  - $ref: '../../../parameters.yaml#/page_size_query_param'
responses:
  '200':
    description: The request was a success.
    content:
      application/json:
        schema:
          $ref: ../../../schemas/responses/list_manifests_response_body.yaml
  '400':
    $ref: ../../../responses/bad_request.yaml
  '404':
    $ref: ../../../responses/not_found.yaml
  '500':
    $ref: ../../../responses/server_error.yaml
