title: dhl_express_account_settings
type: object
additionalProperties: false
properties:
  nickname:
    type: string
  should_hide_account_number_on_archive_doc:
    type: boolean
  is_primary_account:
    type: boolean
