title: package
type: object
required:
  - name
properties:
  package_id:
    allOf:
      - $ref: 'primitives.yaml#/se_id'
    description: A string that uniquely identifies the package id
  package_code:
    type: string
  name:
    type: string
  dimensions:
    allOf:
      - $ref: dimensions.yaml
  description:
    type: string
