title: package
type: object
description: 'A package associated with a [shipping label](https://docs.shipengine.com/docs/quickstart-create-a-label)'
required:
  - weight
additionalProperties: false
properties:
  package_code:
    allOf:
      - $ref: 'primitives.yaml#/package_code'
    description: |
      The [package type](https://docs.shipengine.com/docs/list-carrier-package-types), such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc.  The code `package` indicates a custom or unknown package type.
  weight:
    allOf:
      - $ref: weight.yaml
    description: The package weight
  dimensions:
    allOf:
      - $ref: dimensions.yaml
    description: The package dimensions
  insured_value:
    allOf:
      - $ref: monetary_value.yaml
    default:
      - currency: usd
        amount: 0
    description: |
      The insured value of the package.  Requires the `insurance_provider` field of the shipment to be set.
  tracking_number:
    readOnly: true
    allOf:
      - $ref: 'primitives.yaml#/tracking_number'
    description: |
      The tracking number for the package.  The format depends on the carrier.
  label_messages:
    type: object
    description: |
      Custom messages to print on the shipping label for the package.  These are typically used to print invoice numbers, product numbers, or other internal reference numbers.  Not all carriers support label messages. The number of lines and the maximum length of each line also varies by carrier.

      |Carrier            |Max lines |Max line length
      |-------------------|----------|--------------------
      |USPS (Stamps.com)  |3         |60
      |FedEx              |3         |35 for the first line. 30 for additional lines.
      |UPS                |2         |35
      |OnTrac             |2         |25
    required:
      - reference1
      - reference2
      - reference3
    additionalProperties: false
    properties:
      reference1:
        type: string
        nullable: true
        default: null
        description: |
          The first line of the custom label message.  Some carriers may prefix this line with something like "REF", "Reference", "Trx Ref No.", etc.
      reference2:
        type: string
        nullable: true
        default: null
        description: |
          The second line of the custom label message.  Some carriers may prefix this line with something like "INV", "Reference 2", "Trx Ref No.", etc.
      reference3:
        type: string
        nullable: true
        default: null
        description: |
          The third line of the custom label message.  Some carriers may prefix this line with something like "PO", "Reference 3", etc.
