batch_id_path_param:
  name: batch_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
batch_id_query_param:
  name: batch_id
  in: query
  required: false
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
carrier_code_query_param:
  name: carrier_code
  in: query
  required: false
  schema:
    type: string
carrier_id_path_param:
  name: carrier_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
carrier_id_query_param:
  name: carrier_id
  in: query
  required: false
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
created_at_end_query_param:
  name: created_at_end
  in: query
  required: false
  schema:
    type: string
    format: date-time
created_at_start_query_param:
  name: created_at_start
  in: query
  required: false
  schema:
    type: string
    format: date-time
label_id_path_param:
  name: label_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
modified_at_start_query_param:
  name: modified_at_start
  in: query
  required: false
  schema:
    type: string
    format: date-time
modified_at_end_query_param:
  name: modified_at_end
  in: query
  required: false
  schema:
    type: string
    format: date-time
package_id_path_param:
  name: package_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
page_query_param:
  name: page
  in: query
  required: false
  schema:
    type: integer
    format: int32
    minimum: 1
    default: 1
  example: 2
  description: |
    Return a specific page of results. Defaults to the first page. If set to a number that's greater than the number of pages of results, an empty page is returned.
page_size_query_param:
  name: page_size
  in: query
  required: false
  schema:
    type: integer
    format: int32
    minimum: 1
    default: 25
  example: 50
  description: The number of results to return per response.
pagesize_query_param:
  name: pagesize
  in: query
  required: false
  schema:
    type: integer
    format: int32
rate_id_path_param:
  name: rate_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
shipment_id_path_param:
  name: shipment_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
sort_dir_query_param:
  name: sort_dir
  in: query
  required: false
  schema:
    allOf:
      - $ref: 'schemas/enums.yaml#/sort_dir'
    default: desc
  description: Controls the sort order of the query.
tag_query_param:
  name: tag
  in: query
  required: false
  schema:
    type: string
tag_name_path_param:
  name: tag_name
  in: path
  required: true
  schema:
    type: string
tracking_number_query_param:
  name: tracking_number
  in: query
  required: false
  schema:
    type: string
warehouse_id_path_param:
  name: warehouse_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
warehouse_id_query_param:
  name: warehouse_id
  in: query
  required: false
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
webhook_id_path_param:
  name: webhook_id
  in: path
  required: true
  schema:
    $ref: 'schemas/primitives.yaml#/se_id'
