name: Node/NPM CI

on: 
  push:
    branches: 
      - master

permissions:
  id-token: write # Required for Trusted Publishing
  contents: write # Required to create releases and push tags
  actions: read # used by nx-set-shas
  pull-requests: write # Required to comment on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm publish
      run: npm publish
