name: Node/NPM CI

on:
  push:
    branches:
      - master

permissions:
  id-token: write # Required for Trusted Publishing
  contents: write # Required to create releases and push tags
  actions: read # used by nx-set-shas
  pull-requests: write # Required to comment on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.11.0
        uses: actions/setup-node@v4
        with:
          node-version: "24.11.0"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm with provenance
        run: npm publish --provenance --access public
